apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
   - name: http
     port: 3000
     targetPort: 80
     nodePort: 30001
     protocol: TCP